name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  carousel_slider: ^4.2.1
  chips_choice: ^3.0.1
  flutter:
    sdk: flutter
  # For adding svg
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  #api
  http: ^1.2.1
  image_picker: ^1.1.2
  #format
  intl: ^0.19.0
  #others
  material_symbols_icons: ^4.2762.0
  tuple: ^2.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.2
  toastification: ^2.0.0
  jwt_decoder: ^2.0.1
  widget_and_text_animator: ^1.1.5
  smooth_page_indicator: ^1.1.0
  path: ^1.9.0
  mime: ^1.0.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  glassmorphism: ^3.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/drawer_menu_icon/
