name: frontend_ad
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  provider: ^6.1.2
  intl: ^0.17.0
  image_picker: ^1.1.2
  glassmorphism_ui: ^0.3.0
  glassmorphism: ^3.0.0
  toastification: ^2.0.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  widget_and_text_animator: ^1.1.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - images/
